System hostname = openbsd78
Password for root = vagrant
Allow root ssh login = yes
Setup a user = vagrant
Password for user = vagrant
Public ssh key for user = https://raw.githubusercontent.com/hashicorp/vagrant/main/keys/vagrant.pub
Do you expect to run the X Window System = no
What timezone are you in = UTC
Which disk is the root disk = sd0
Encrypt the root disk = no
Use (W)hole disk MBR, whole disk (G)PT or (E)dit = whole
Location of sets = http
HTTP Server = cdn.openbsd.org
Set name(s) = -game* -x*
Directory does not contain SHA256.sig. Continue without verification = yes
